// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/photosync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PhotoSync_RegisterAgent_FullMethodName     = "/photosync.PhotoSync/RegisterAgent"
	PhotoSync_Heartbeat_FullMethodName         = "/photosync.PhotoSync/Heartbeat"
	PhotoSync_UpdateAgentStatus_FullMethodName = "/photosync.PhotoSync/UpdateAgentStatus"
	PhotoSync_DiscoverPhotos_FullMethodName    = "/photosync.PhotoSync/DiscoverPhotos"
	PhotoSync_GetPhotoMetadata_FullMethodName  = "/photosync.PhotoSync/GetPhotoMetadata"
	PhotoSync_SyncPhotoMetadata_FullMethodName = "/photosync.PhotoSync/SyncPhotoMetadata"
	PhotoSync_UploadPhoto_FullMethodName       = "/photosync.PhotoSync/UploadPhoto"
	PhotoSync_DownloadPhoto_FullMethodName     = "/photosync.PhotoSync/DownloadPhoto"
	PhotoSync_BatchSync_FullMethodName         = "/photosync.PhotoSync/BatchSync"
	PhotoSync_GetSyncQueue_FullMethodName      = "/photosync.PhotoSync/GetSyncQueue"
	PhotoSync_GetAgentStatus_FullMethodName    = "/photosync.PhotoSync/GetAgentStatus"
	PhotoSync_GetServerStats_FullMethodName    = "/photosync.PhotoSync/GetServerStats"
)

// PhotoSyncClient is the client API for PhotoSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PhotoSync service for distributed photo management
type PhotoSyncClient interface {
	// Agent Management
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*UpdateAgentStatusResponse, error)
	// Photo Discovery and Metadata
	DiscoverPhotos(ctx context.Context, in *DiscoverPhotosRequest, opts ...grpc.CallOption) (*DiscoverPhotosResponse, error)
	GetPhotoMetadata(ctx context.Context, in *GetPhotoMetadataRequest, opts ...grpc.CallOption) (*GetPhotoMetadataResponse, error)
	SyncPhotoMetadata(ctx context.Context, in *SyncPhotoMetadataRequest, opts ...grpc.CallOption) (*SyncPhotoMetadataResponse, error)
	// Binary Photo Transfer (Streaming)
	UploadPhoto(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPhotoRequest, UploadPhotoResponse], error)
	DownloadPhoto(ctx context.Context, in *DownloadPhotoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadPhotoResponse], error)
	// Batch Operations
	BatchSync(ctx context.Context, in *BatchSyncRequest, opts ...grpc.CallOption) (*BatchSyncResponse, error)
	GetSyncQueue(ctx context.Context, in *GetSyncQueueRequest, opts ...grpc.CallOption) (*GetSyncQueueResponse, error)
	// Status and Monitoring
	GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error)
	GetServerStats(ctx context.Context, in *GetServerStatsRequest, opts ...grpc.CallOption) (*GetServerStatsResponse, error)
}

type photoSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewPhotoSyncClient(cc grpc.ClientConnInterface) PhotoSyncClient {
	return &photoSyncClient{cc}
}

func (c *photoSyncClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, PhotoSync_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoSyncClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, PhotoSync_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoSyncClient) UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*UpdateAgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAgentStatusResponse)
	err := c.cc.Invoke(ctx, PhotoSync_UpdateAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoSyncClient) DiscoverPhotos(ctx context.Context, in *DiscoverPhotosRequest, opts ...grpc.CallOption) (*DiscoverPhotosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverPhotosResponse)
	err := c.cc.Invoke(ctx, PhotoSync_DiscoverPhotos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoSyncClient) GetPhotoMetadata(ctx context.Context, in *GetPhotoMetadataRequest, opts ...grpc.CallOption) (*GetPhotoMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhotoMetadataResponse)
	err := c.cc.Invoke(ctx, PhotoSync_GetPhotoMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoSyncClient) SyncPhotoMetadata(ctx context.Context, in *SyncPhotoMetadataRequest, opts ...grpc.CallOption) (*SyncPhotoMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncPhotoMetadataResponse)
	err := c.cc.Invoke(ctx, PhotoSync_SyncPhotoMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoSyncClient) UploadPhoto(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPhotoRequest, UploadPhotoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PhotoSync_ServiceDesc.Streams[0], PhotoSync_UploadPhoto_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadPhotoRequest, UploadPhotoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhotoSync_UploadPhotoClient = grpc.ClientStreamingClient[UploadPhotoRequest, UploadPhotoResponse]

func (c *photoSyncClient) DownloadPhoto(ctx context.Context, in *DownloadPhotoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadPhotoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PhotoSync_ServiceDesc.Streams[1], PhotoSync_DownloadPhoto_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadPhotoRequest, DownloadPhotoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhotoSync_DownloadPhotoClient = grpc.ServerStreamingClient[DownloadPhotoResponse]

func (c *photoSyncClient) BatchSync(ctx context.Context, in *BatchSyncRequest, opts ...grpc.CallOption) (*BatchSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSyncResponse)
	err := c.cc.Invoke(ctx, PhotoSync_BatchSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoSyncClient) GetSyncQueue(ctx context.Context, in *GetSyncQueueRequest, opts ...grpc.CallOption) (*GetSyncQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncQueueResponse)
	err := c.cc.Invoke(ctx, PhotoSync_GetSyncQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoSyncClient) GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentStatusResponse)
	err := c.cc.Invoke(ctx, PhotoSync_GetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photoSyncClient) GetServerStats(ctx context.Context, in *GetServerStatsRequest, opts ...grpc.CallOption) (*GetServerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerStatsResponse)
	err := c.cc.Invoke(ctx, PhotoSync_GetServerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhotoSyncServer is the server API for PhotoSync service.
// All implementations must embed UnimplementedPhotoSyncServer
// for forward compatibility.
//
// PhotoSync service for distributed photo management
type PhotoSyncServer interface {
	// Agent Management
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	UpdateAgentStatus(context.Context, *UpdateAgentStatusRequest) (*UpdateAgentStatusResponse, error)
	// Photo Discovery and Metadata
	DiscoverPhotos(context.Context, *DiscoverPhotosRequest) (*DiscoverPhotosResponse, error)
	GetPhotoMetadata(context.Context, *GetPhotoMetadataRequest) (*GetPhotoMetadataResponse, error)
	SyncPhotoMetadata(context.Context, *SyncPhotoMetadataRequest) (*SyncPhotoMetadataResponse, error)
	// Binary Photo Transfer (Streaming)
	UploadPhoto(grpc.ClientStreamingServer[UploadPhotoRequest, UploadPhotoResponse]) error
	DownloadPhoto(*DownloadPhotoRequest, grpc.ServerStreamingServer[DownloadPhotoResponse]) error
	// Batch Operations
	BatchSync(context.Context, *BatchSyncRequest) (*BatchSyncResponse, error)
	GetSyncQueue(context.Context, *GetSyncQueueRequest) (*GetSyncQueueResponse, error)
	// Status and Monitoring
	GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error)
	GetServerStats(context.Context, *GetServerStatsRequest) (*GetServerStatsResponse, error)
	mustEmbedUnimplementedPhotoSyncServer()
}

// UnimplementedPhotoSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPhotoSyncServer struct{}

func (UnimplementedPhotoSyncServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedPhotoSyncServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPhotoSyncServer) UpdateAgentStatus(context.Context, *UpdateAgentStatusRequest) (*UpdateAgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgentStatus not implemented")
}
func (UnimplementedPhotoSyncServer) DiscoverPhotos(context.Context, *DiscoverPhotosRequest) (*DiscoverPhotosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverPhotos not implemented")
}
func (UnimplementedPhotoSyncServer) GetPhotoMetadata(context.Context, *GetPhotoMetadataRequest) (*GetPhotoMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhotoMetadata not implemented")
}
func (UnimplementedPhotoSyncServer) SyncPhotoMetadata(context.Context, *SyncPhotoMetadataRequest) (*SyncPhotoMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncPhotoMetadata not implemented")
}
func (UnimplementedPhotoSyncServer) UploadPhoto(grpc.ClientStreamingServer[UploadPhotoRequest, UploadPhotoResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadPhoto not implemented")
}
func (UnimplementedPhotoSyncServer) DownloadPhoto(*DownloadPhotoRequest, grpc.ServerStreamingServer[DownloadPhotoResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadPhoto not implemented")
}
func (UnimplementedPhotoSyncServer) BatchSync(context.Context, *BatchSyncRequest) (*BatchSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchSync not implemented")
}
func (UnimplementedPhotoSyncServer) GetSyncQueue(context.Context, *GetSyncQueueRequest) (*GetSyncQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncQueue not implemented")
}
func (UnimplementedPhotoSyncServer) GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentStatus not implemented")
}
func (UnimplementedPhotoSyncServer) GetServerStats(context.Context, *GetServerStatsRequest) (*GetServerStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStats not implemented")
}
func (UnimplementedPhotoSyncServer) mustEmbedUnimplementedPhotoSyncServer() {}
func (UnimplementedPhotoSyncServer) testEmbeddedByValue()                   {}

// UnsafePhotoSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhotoSyncServer will
// result in compilation errors.
type UnsafePhotoSyncServer interface {
	mustEmbedUnimplementedPhotoSyncServer()
}

func RegisterPhotoSyncServer(s grpc.ServiceRegistrar, srv PhotoSyncServer) {
	// If the following call panics, it indicates UnimplementedPhotoSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PhotoSync_ServiceDesc, srv)
}

func _PhotoSync_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoSync_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoSync_UpdateAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).UpdateAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_UpdateAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).UpdateAgentStatus(ctx, req.(*UpdateAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoSync_DiscoverPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).DiscoverPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_DiscoverPhotos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).DiscoverPhotos(ctx, req.(*DiscoverPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoSync_GetPhotoMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhotoMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).GetPhotoMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_GetPhotoMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).GetPhotoMetadata(ctx, req.(*GetPhotoMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoSync_SyncPhotoMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncPhotoMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).SyncPhotoMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_SyncPhotoMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).SyncPhotoMetadata(ctx, req.(*SyncPhotoMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoSync_UploadPhoto_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PhotoSyncServer).UploadPhoto(&grpc.GenericServerStream[UploadPhotoRequest, UploadPhotoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhotoSync_UploadPhotoServer = grpc.ClientStreamingServer[UploadPhotoRequest, UploadPhotoResponse]

func _PhotoSync_DownloadPhoto_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadPhotoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PhotoSyncServer).DownloadPhoto(m, &grpc.GenericServerStream[DownloadPhotoRequest, DownloadPhotoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhotoSync_DownloadPhotoServer = grpc.ServerStreamingServer[DownloadPhotoResponse]

func _PhotoSync_BatchSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).BatchSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_BatchSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).BatchSync(ctx, req.(*BatchSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoSync_GetSyncQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).GetSyncQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_GetSyncQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).GetSyncQueue(ctx, req.(*GetSyncQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoSync_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_GetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).GetAgentStatus(ctx, req.(*GetAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotoSync_GetServerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotoSyncServer).GetServerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhotoSync_GetServerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotoSyncServer).GetServerStats(ctx, req.(*GetServerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhotoSync_ServiceDesc is the grpc.ServiceDesc for PhotoSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhotoSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "photosync.PhotoSync",
	HandlerType: (*PhotoSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _PhotoSync_RegisterAgent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _PhotoSync_Heartbeat_Handler,
		},
		{
			MethodName: "UpdateAgentStatus",
			Handler:    _PhotoSync_UpdateAgentStatus_Handler,
		},
		{
			MethodName: "DiscoverPhotos",
			Handler:    _PhotoSync_DiscoverPhotos_Handler,
		},
		{
			MethodName: "GetPhotoMetadata",
			Handler:    _PhotoSync_GetPhotoMetadata_Handler,
		},
		{
			MethodName: "SyncPhotoMetadata",
			Handler:    _PhotoSync_SyncPhotoMetadata_Handler,
		},
		{
			MethodName: "BatchSync",
			Handler:    _PhotoSync_BatchSync_Handler,
		},
		{
			MethodName: "GetSyncQueue",
			Handler:    _PhotoSync_GetSyncQueue_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _PhotoSync_GetAgentStatus_Handler,
		},
		{
			MethodName: "GetServerStats",
			Handler:    _PhotoSync_GetServerStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadPhoto",
			Handler:       _PhotoSync_UploadPhoto_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadPhoto",
			Handler:       _PhotoSync_DownloadPhoto_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/photosync.proto",
}
